# cat /base/applications/monitoring/fluxcd-gitrepo.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-monitoring
  namespace: monitoring
spec:
  interval: 30m0s
  ref:
    branch: main
  timeout: 60s
  url: https://github.com/fluxcd/flux2
